apiVersion: v1
kind: Service
metadata:
  name: goapp
  namespace: default
spec:
  selector:
    app: goapp
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: goapp
      protocol: TCP
      port: 8080
      targetPort: 8080
